### ISSUE TITLE
Support non-ASCII domain names

### ISSUE THREAD

**Issue by jplot** [c-mueller/ads#28]
https://github.com/c-mueller/ads/blob/a91567464d421289f5590916b4a5a8028f18c524/list_map_handler.go#L30

`https://someonewhocares.org/hosts/zero/hosts` `https://en.wiktionary.org/wiki/%C9%A2`
```
ɢoogle.com
```

**Comment by c-mueller** [comment]
this filter expression is still intentional. As far as i understand the problem can currently be resolved by using the ascii encoded domain name instead, within the list. In the example you provided this would be:
```
xn--oogle-wmc.com
```
I personally do not see a huge hazard in keeping these domains, since they seem to be used for malicious purposes and not for serving ads. Mitigation for "homographic attacks" are also in place elsewhere.

However due to the current situation and tha fact that I am kinda bored I will still implement this ASAP.

Gain thank you for the contribution.

Some notes for implementation:
Potential IDNA decoder: https://godoc.org/golang.org/x/net/idna

**Comment by c-mueller** [comment]
Alright. This should be implemented in the latest PR. Non ascii names can now also be used to perit/block using the corefile itself. For example:
```
block mähl.de
```
gets blocked, when looking it up using `dig mähl.de`
