### ISSUE TITLE
hi,c-mueller!

### ISSUE THREAD

**Issue by snakwu** [c-mueller/ads#37]
hi,c-mueller!
When I add ads to the source code of coerdns, and then make, no matter whether my Corefile is added or not, the entire network becomes slow!

**plugin.cfg**

metadata:metadata
cancel:cancel
tls:tls
reload:reload
nsid:nsid
bufsize:bufsize
root:root
bind:bind
debug:debug
trace:trace
ready:ready
health:health
pprof:pprof
prometheus:metrics
errors:errors
log:log
dnstap:dnstap
dns64:dns64
acl:acl
any:any
chaos:chaos
loadbalance:loadbalance
cache:cache
rewrite:rewrite
dnssec:dnssec
autopath:autopath
template:template
transfer:transfer
ads:github.com/c-mueller/ads
hosts:hosts
clouddns:clouddns
k8s_external:k8s_external
kubernetes:kubernetes
file:file
auto:auto
secondary:secondary
etcd:etcd
loop:loop
fanout:github.com/networkservicemesh/fanout
forward:forward
grpc:grpc
erratic:erratic
whoami:whoami
on:github.com/caddyserver/caddy/onevent
sign:sign

**Comment by snakwu** [comment]
I may know that the reason is there. This may have something to do with ipv6. I should talk about my environment. I filled in the intranet address of coerdns for the dns on the route, and the dns filled in the child device is the routed address!

**Comment by c-mueller** [comment]
Hey there,
I am sorry for the late reply, but I have been busy doing other things. While I am still unable to understand the cause of the problem, i think i might have encountered the same issue in my own installation. In order to get an idea what causes this, I have some questions regarding your installation:

- What Operating System (distribution) and Version are you using?
    - Including the version (e.g. Ubuntu 18.04)
-  How large is your set of blocked and whitelisted URLs?
   - This should be displayed when launching CoreDNS with the plugin enabled.
- Do you use Regex rules?
- Do you define any rules in the Corefile itself, by using `permit` or `block`?
- Is the slowdown consistent i.e. all the time, or does it seem to go away from time to time?
- Does your coredns instance serve Multiple instances of the `ads` plugin

**Comment by snakwu** [comment]
> 嘿，
> 很抱歉收到您的答复，但我一直在忙着做其他事情。虽然我仍然无法理解问题的原因，但我认为自己的安装中可能遇到了相同的问题。为了弄清是什么原因，我对您的安装有一些疑问：
> 
> * 您正在使用什么操作系统（发行版）和版本？
>   
>   * 包括版本（例如Ubuntu 18.04）
> * 您的一组被阻止和列入白名单的URL有多大？
>   
>   * 在启用了插件的情况下启动CoreDNS时，应该显示此信息。
> * 您使用正则表达式规则吗？
> * 您是否通过使用`permit`或在Corefile中定义了任何规则`block`？
> * 减速是否始终如一，还是似乎不时消失？
> * 您的coredns实例是否服务`ads`插件的多个实例

I use ubuntu18.0.4, is always slow, I do not use formal regular expressions, the rules are https://github.com/privacy-protection-tools/anti-AD，Forum ads such as bbs.91wall.com, cannot be removed.

**Comment by snakwu** [comment]
@c-mueller 
1.What Operating System (distribution) and Version are you using?
->Ubuntu 18.04
2.How large is your set of blocked and whitelisted URLs?
->https://github.com/privacy-protection-tools/anti-AD
3.Do you use Regex rules?
->no
4.Do you define any rules in the Corefile itself, by using permit or block?
->no
5.Is the slowdown consistent i.e. all the time, or does it seem to go away from time to time?
->all the time
6.Does your coredns instance serve Multiple instances of the ads plugin
->only
