### ISSUE TITLE
Change Blocklist store to use different "storage" adapters

### ISSUE THREAD

**Issue by c-mueller** [c-mueller/ads#4]
Consider the use of some sort of storage adapters for the block list like:

Some could be:

Based on a External storage solution
- SQL
- BoltDB
- Redis
- LevelDB

Based on Filesystem storage
- JSON (Used currently)
- Protobufs

We could also investigate the use of lookup through the storage solution, instead of loading the whole blocklist in memory

**Comment by dichro** [comment]
github.com/syndtr/goleveldb/leveldb is very fast and manages its own in-memory caching. You could store blocklists in leveldb and query it directly in the DNS query path, rather than storing them in memory or doing your own caching, and this should have very little performance impact compared to typical DNS lookup.

**Comment by c-mueller** [comment]
Thanks for your suggestion. I will take a look at it.
