### ISSUE TITLE
Improve Exposed Metrics: Add a new metric for blocked request at a given moment

### ISSUE THREAD

**Issue by thibaltus** [c-mueller/ads#43]
First of all, thanks you to has spend time on this project, your plugin convince me to switch from pi-hole to CoreDns as my home dns !! 

I have setup a graphana dashboard for my CoreDns instance, and i would like to be able to have the number of blocked request at a given moment. There is only two metrics exported for now `coredns_ads_blocked_request_count_total` and `coredns_ads_request_count_total`; unfortunately these metrics does not fit my need

I have juste read the documentation of prometheus, for this need you should need to use [histogram metric](https://prometheus.io/docs/concepts/metric_types/#histogram) 

If you don't have enough time to do this it's not a problem, i could try to work on it (event if i am not really comfortable with go language )

Once again, thanks for sharing with us your work :1st_place_medal:

**Comment by c-mueller** [comment]
Hey there,

Sorry for my really late reply, I replied via mail the last time, but for whatever reason it did not work properly.

Personally i am currently busy with other tihngs, for that reason i cannot guarantee that i will implement this feature in the near future.

If you have the time, feel free to do it yourself, any contributions are appreciated.

BTW: it is good to hear that the prometheus metrics have any use, since i never used them myself.
